on:
  workflow_dispatch:
    inputs:
      dry_run:
        default: true
        type: boolean
        description: set dry run to see the output without actually scheduling deletion
      days_before_branch_delete:
        default: 7
        description: How many days to wait before deleting the branches Set to 0 to delete immediately.

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          dry-run: ${{ github.event.inputs.dry_run }} 
          exempt-branches-regex: (auth|master)
          days-before-branch-delete: ${{ github.event.inputs.days_before_branch_delete }}
          days-before-branch-stale: 30
          operations-per-run: 3000